### ISSUE TITLE
Recipe doesn't archive items despite having archive_downloaded = True

### ISSUE THREAD

**Issue by alvaroreig** [mmagnus/Pocket-Plus-Calibre-Plugin#16]
Hi there,

Since a couple of weeks ago I have noticed that articles are no longer archived despite having "archive_downloaded = True" in the recipe.

I have tried with crofflr and it doesn't seem to work as well, maybe the Pocket team changed something in the API?

Thank you, regards.

**Comment by mmagnus** [comment]
OK, I'll take a look

**Comment by mmagnus** [comment]
@alvaroreig  can you try again? I think it works right now. It seems that, in my case, Pocket on OSX shows 136 articles, but https://app.getpocket.com looks ok.

**Comment by alvaroreig** [comment]
Hi @mmagnus 

I have done my testing and my conclusions are:

TAGS = [''], to_pull = 'all' => OK
TAGS = [''], to_pull = 'unread' => OK
TAGS = ['','tag1','tag2'], to_pull = 'unread' => OK
TAGS = ['tag1','tag2'], to_pull = 'unread' => NOT OK. It archives the articles of (aparently) tag2 but not tag1. That is the conf. I was using.

Therefore, to solve it I will just add '' to the TAGS list.

Thanks a lot!.

Regards,

**Comment by alvaroreig** [comment]
Hi again @mmagnus ,

My environment is behaving quite strangely (tags that show up and dissapear for example). Can you share your:

- Calibre version
- Python version
- tags,oldest_article, max_articles_per_feed, sort_method,to_pull settings?

I am going crazy over here.

Thanks a lot,

**Comment by mmagnus** [comment]
Yeah, dear @alvaroreig I'm also trying now with different options. 

I have the same problem:

```
TAGS = ['', 'tag']
ARCHIVE_DOWNLOADED = True
MAX_ARTICLES_PER_FEED = 2
SORT_METHOD = 'newest'
TO_PULL = 'unread'
```

Results: Error! Tag is archived, but 2 Arts not!

So I'm trying to find how to fix it.

One workaround for each Tag or '' to have own Pocket Recipe. So copy the file of Recipe and have one for '' and then second with different settings for Tag1 or Tag2. But yeah, it's not perfect...

**Comment by mmagnus** [comment]
.. and I think when the articles are downloaded as '' (The latest) then it will not be downloaded as Tagged (if  `ARCHIVE_DOWNLOADED = True`)..

**Comment by alvaroreig** [comment]
Hi @mmagnus 

I've been testing your workaround and I can confirm your solution:

- TAGS = ['tag1'] => OK
- TAGS = ['tag1'...['tagn'] => Every article is correctly downloaded, but only tagn is archived.

Therefore, for the time being we have to chose between:

- One ebook/recipe per tag
- All the tags together in a single recipe, archive_download=false, and play with oldest_article to avoid downloading duplicate content.

I will use the first one for now. If it can be fixed it would be great, but I can live with this workaround.

Thanks a lot!
