### ISSUE TITLE
No Option to Log In

### ISSUE THREAD

**Issue by Tamarissa** [mmagnus/Pocket-Plus-Calibre-Plugin#17]
I've installed the recipe, and when I click 'Download Now', nothing happens. The pop-up window asking me to log in to Pocket account doesn't appear.

Attached is the debug file from Calibre:
[tmpJJOsoa.txt](https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/files/4612704/tmpJJOsoa.txt)

**Comment by mmagnus** [comment]
Try this:

"if the window disappears, it might be behind the main window of Calibre"

The window might be there, simply under Calibre. 
(I also had a problem with this and then I realized that the window was there)

https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin

**Comment by Tamarissa** [comment]
There is no login window hiding behind Calibre; as such this issue is not resolved and should not have been closed.

As it will show in the debug file previously attached, Calibre shows the pop-up window stating it is processing the request to Pocket, which it can't actually do ask no login info was provided.

**Comment by mmagnus** [comment]
did you clicked on this?

https://getpocket.com/auth/authorize?request_token=43ae55a8-91f9-dc11-b2d1-123730&redirect_uri=https://calibre-ebook.com/

**Comment by mmagnus** [comment]
<img width="831" alt="Screen Shot 2020-05-19 at 9 43 39 PM" src="https://user-images.githubusercontent.com/118740/82371091-e7151580-9a19-11ea-86e9-4fe82401316c.png">
