### ISSUE TITLE
Fix missing titles

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/Pocket-Plus-Calibre-Plugin#22]
> It will be because auto_cleanup is removing it, either dont use
> auto_cleanup or add auto_cleanup_keep

from kovid@kovidgoyal.net

**Comment by Monirzadeh** [comment]
clean up use caliber to clean the web view?
what do think about [this solution](https://github.com/fivefilters/ftr-site-config)?

**Comment by mmagnus** [comment]
@Monirzadeh  yeah, something like that.. or just a simple hack to copy <title> from the article into the main text to create <h1>, I hacked something like this.. but still it's super ugly. I think that would be enough, the script by itself deals with most of the pages very well, in my opinion.
