### ISSUE TITLE
sort order options

### ISSUE THREAD

**Issue by ssd2** [mmagnus/Pocket-Plus-Calibre-Plugin#25]
For most tags, sorting oldest or newest is great.
However, I've got a few tags where sorting by title (or post date rather than bookmark date?) would be a lot better.  I don't know if there are other useful sortable attributes.

This would be a great enchancement.

**Comment by mmagnus** [comment]
OK, I got something to sort by title things that are downloaded based on your config. 

So this is important! The articles are sorted after being downloaded, so this does not work on articles in Pocket. So if you MAX_ARTICLES_PER_FEED = 2 for example, first it will fetch 2 articles based on your configuration and they will be sorted. 

So this might do what you want, but this depends on all of these variables:

    MAX_ARTICLES_PER_FEED = 30 
    OLDEST_ARTICLE = 7
    SORT_METHOD = 'newest'
    TO_PULL = 'unread'

**Comment by ssd2** [comment]
For the tags I'd like to sort by title, the number of articles is less than MAX_ARTICLES_PER_FEED so that's not too big of a deal.

**Comment by mmagnus** [comment]
Yeah, this is what I thought.

So this is what you wanted? :-) @ssd2

**Comment by ssd2** [comment]
I'll have to test it again.  First time I tested, it didn't succeed in downloading any articles for some reason.

**Comment by mmagnus** [comment]
OK, let me know if it works, if not, then I will re-open this issue :-)
