### ISSUE TITLE
UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by tvqt** [mmagnus/Pocket-Plus-Calibre-Plugin#28]
Hi there, 

I recently got a Mac for the first time, and installed calibre + pocket plus, as i did on my old pc. for some reason, the plugin doesn't seem to work! the error log is below

Things I've tried:
- changing the output profile
- using the old version of the plugin
- playing around with the code a bit (I know a bit of Python, but I'm in over my head lol)

Thoughts:
- It could be user error (I could have overlooked something)
- I'm using the new ARM-based Macbook Air, so maybe there's an issue there (?)

Any help is much appreciated!

Love your work!

---
calibre, version 5.7.2 (darwin, embedded-python: True)
Conversion error: Failed: Fetch news from Pocket

Fetch news from Pocket
Conversion options changed from defaults:
  verbose: 2
  output_profile: 'kindle_voyage'
Resolved conversion options
calibre version: 5.7.2
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'dont_download_recipe': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x12101c190>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindleVoyageOutput object at 0x12101c7c0>,
 'page_breaks_before': None,
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Downloading recipe urn: custom:1000
Using user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 216, in main
  File "calibre/gui2/convert/gui_conversion.py", line 34, in gui_convert_recipe
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/recipe_input.py", line 139, in convert
  File "calibre/web/feeds/news.py", line 1051, in download
  File "calibre/web/feeds/news.py", line 1220, in build_index
  File "<string>", line 284, in parse_index
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by tvqt** [comment]
update: i installed Calibre 4.32, and an Pocket Plus 2.31, and they both work! I'm gonna see if I can narrow it down to a particular version of either

**Comment by mmagnus** [comment]
Dear @tvqt 

For me:

    Plugin version: 2.6.3
    Calibre 5.5.0
    Mac Catalina 10.15.7
    
it works. The plugin should work with these (new) versions. If you use older versions, we did have various problems on the way, so that you could stumble on one of them. Let me know if there is a problem with the updated versions of the plugin and Calibre.

**Comment by tvqt** [comment]
yeah, the 

> Dear @tvqt
> 
> For me:
> 
> ```
> Plugin version: 2.6.3
> Calibre 5.5.0
> Mac Catalina 10.15.7
> ```
> 
> it works. The plugin should work with these (new) versions. If you use older versions, we did have various problems on the way, so that you could stumble on one of them. Let me know if there is a problem with the updated versions of the plugin and Calibre.

(at least in my experience) there seems to be some kind of issue. I had a bit of a play around with different versions yesterday; one (I think version 2.5.2?) seemed to find articles, but then was trying to download everything, when I set the max to 1 ^_^

The bug was with the most updated version of everything ( calibre 5.7.2, Pocket Plus 2.6.3, MacOS Big Sur 11.0). I'll download Calibre 5.50 later today and see if the bug disappears
