### ISSUE TITLE
KeyError: 'resolved_title'

### ISSUE THREAD

**Issue by nhohung** [mmagnus/Pocket-Plus-Calibre-Plugin#33]
Hello,

This is my first try of the plugin and it doesn't seem to work. The error is: `KeyError: 'resolved_title'`.

My unarchived list has about 25 articles. I tested the latest Calibre 5.17 on my Windows laptop and an older version 3.48 on my Mac (High Sierra) without any luck. In both cases, the latest plugin is used (2.7.1).

At first I thought for some reason the title is not parsed correctly by unsupported unicode character (1 article has a few Chinese characters). Digging in the discussion I found it fixed in 2017. Just to be sure, I removed that article and still got the same error.

What I've also tried but not help:
- Archieve most of the articles, leaving only 5
- Uncheck Schedule downloading
- Check/Uncheck Add title as flag option

Reading other issues I suspect the version compatibility between Calibre and PocketPlus plugin but I'm a bit lost. Can you please guide me where to start? Thanks!

Here is the error log on my Windows machine:

```
calibre, version 5.17.0 (win32, embedded-python: True)
Conversion error: Failed: Fetch news from Pocket

Fetch news from Pocket
Conversion options changed from defaults:
  output_profile: 'kindle_pw3'
  verbose: 2
Resolved conversion options
calibre version: 5.17.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'dont_download_recipe': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x07D752C8>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x07D755C8>,
 'page_breaks_before': None,
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Downloading recipe urn: custom:1000
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 216, in main
  File "calibre\gui2\convert\gui_conversion.py", line 34, in gui_convert_recipe
  File "calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1105, in run
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\recipe_input.py", line 139, in convert
  File "calibre\web\feeds\news.py", line 1051, in download
  File "calibre\web\feeds\news.py", line 1220, in build_index
  File "<string>", line 340, in parse_index
KeyError: 'resolved_title'
```

**Comment by nhohung** [comment]
When investigating the dictionary `section_dict` that contains articles, I found each article has the following fields as an example:
```
'3325357131': {
	'item_id': '3325357131',
	'resolved_id': '2941500101',
	'given_url': 'https://en.wikipedia.org/wiki/Glacial_lake',
	'given_title': '',
	'favorite': '0',
	'status': '1',
	'time_added': '1620803954',
	'time_updated': '1620851108',
	'time_read': '1620851106',
	'time_favorited': '0',
	'sort_id': 212,
	'resolved_title': 'Glacial lake',
	'resolved_url': 'https://en.wikipedia.org/wiki/Glacial_lake',
	'excerpt': 'A glacial lake is a body of water with origins from glacier activity.',
	'is_article': '1',
	'is_index': '0',
	'has_video': '0',
	'has_image': '0',
	'word_count': '188',
	'lang': 'en',
	'tags': {'2020': {'item_id': '3325357131', 'tag': '2020'}, 'thang04': {'item_id': '3325357131', 'tag': 'thang04'}},
	'listen_duration_estimate': 730
},
```
However I found a weird one:
```
'3329295294': {
	'item_id': '3329295294',
	'status': '2',
	'listen_duration_estimate': 0
},
```
This is the reason for the error `KeyError: 'resolved_title'` because there is no `resolved_title`. Some other required keys are missing too: `resolved_url`, `time_added` and `excerpt`.

I think it relates to `status` of `2`. There are articles with `status` of `0` and `1`. I don't know if this is a kind of flag that should be used to exclude 'ghost' articles(?)

FYI I tried an older version (2.6.3) and there is no issue on both Windows and MacOS. So there must be something with the newer version. I see different ways of handling the dictionary to cope with the newly introduced `section` but I haven't got time to digest the changes from 2.6.3 to 2.7 and later.

I hope the finding above is useful to investigate the problem.

**Comment by nhohung** [comment]
### Current issue

The problem is a bit clearer after I look at the article descriptions on [Pocket API page](https://getpocket.com/developer/docs/v3/retrieve). `status` of `2` indicates item should be deleted. For some reasons `status` of untagged articles after retrieving is `2`.

Digging deeper into the code I found in this version (2.7.1), defining `TAGS` organizes output sections will create a bug when tags are provided along with `INCLUDE_UNTAGGED` turned on. This combination is rare but exists when an user wants to extract specific tags and other untagged articles. Of course this is equivalent to an inverted tag selection into `TAGS_EXCEPTIONS` but I haven't tried this approach.

What happens here is: when _n_ tags are included, `INCLUDE_UNTAGGED` must be `False`. Because if `INCLUDE_UNTAGGED` is `True`, the first _n_ sections are the _n_ declared tags, and the last section (_n+1_) is untagged always returns empty information.

### New issue

I tried a few tags with `INCLUDE_UNTAGGED` turned off and found another bug: it only works with the first tag in multi-tags articles. To be specific, in my Pocket list, I organize items by 2 tags in the following order: **#year** and **#month**. For example, some articles have 2 tags of **2020** and **month04**; while others have **2021** and **month05**. The json tag key for these item looks something like this:
`'tags': {'2020': {'item_id': '3325357131', 'tag': '2020'}, 'month04': {'item_id': '3325357131', 'tag': 'month04'}}`,

- If I want to extract all articles in 2020, I simply put **2020** in `TAGS`, and that works fine because **2020** is the first tag.
- If I want to extract all articles in May, I put **month05** in `TAGS`. This returns no article because **month05** is the second tag and I think the current version only takes the first element as I see at line 308:
`tag = list(response['list'][item]['tags'].keys())[0]`.

The reported error is found to be a small glitch in settings, but reveals a new issue in handling multi-tag articles. I hope this provides initial clues for someone with more experience to fix it.

Have a nice weekend.

**Comment by alvaroreig** [comment]
Hi there @nhohung 

Before testing your PR I tried to replicate these errors.

I can confirm that the plugin only reads the first tag of every article. If I tag 2 articles like that:

Article1 => tag1
Article2 => tag1,tag2

And I set:

TAGS = ['tag1','tag2']

I only get:

tag1 => article1,article2

However, I cant repplicate the second error. In my tests, these configuration:

TAGS = ['tag1','tag2']
INCLUDE_UNTAGGED = True

worked as expected, all the untagged items where correctly grouped under the "Untagged" section

**Comment by nhohung** [comment]
Hi @alvaroreig,

Thank you for confirming the multi-tag glitch. The PR is trying to fix it and not related to the original error message in this issue.

Regarding this issue (`KeyError: 'resolved_title'`), after reading your reply I think there might be one difference between our cases with respect to the `INCLUDE_UNTAGGED` option: you actually have untagged articles while I don't (all articles have at least 1 tag).

I have manually created a new untagged article and tested different scenarios with `TO_PULL` and `INCLUDE_UNTAGGED` option in 2 cases: leave the untagged article in the main list or archive it before running the plug in. My original case with no untagged article is also reproduced. Summary in table below:

Have untagged article? | Untagged article archived? | `TO_PULL` | `INCLUDE_UNTAGGED` | Outcome
-------------------------- | ------------------------------|------------|--------------------------|----------
No (reproduce)              | N/A                                     | **all**       | **True**                        | **Error**
No (reproduce)               | N/A                                     | unread     | True                              | OK
No (reproduce)               | N/A                                     | all             | False                             | OK
No (reproduce)                | N/A                                     | unread     | False                             | OK
Yes                                  | No                                      | **all**       | **True**                        | **Error**
Yes                                  | No                                      | unread     | True                              | OK
Yes                                  | No                                      | all             | False                             | OK
Yes                                  | No                                      | unread     | False                             | OK
Yes                                  | Yes                                      | **all**      | **True**                        | **Error**
Yes                                  | Yes                                      | unread     | True                              | OK
Yes                                  | Yes                                      | all             | False                             | OK
Yes                                  | Yes                                      | unread     | False                             | OK

Apparently the error is caused when `TO_PULL` and `INCLUDE_UNTAGGED` are set to `all` and `True` respectively. If your `TO_PULL` currently is set to `unread`, can you please try `TO_PULL = 'all'` and `INCLUDE_UNTAGGED = True` to see if there is any problem?

Thanks,
Hung

**Comment by mmagnus** [comment]
> Apparently the error is caused when TO_PULL and INCLUDE_UNTAGGED are set to all and True respectively. If your TO_PULL currently is set to unread, can you please try TO_PULL = 'all' and INCLUDE_UNTAGGED = True to see if there is any problem?

Yeah, I can confirm that. OK, I'm also looking how to fix it, Thanks @nhohung for reporting this issue.

```
Conversion options changed from defaults:
  test: None
1% Converting input to HTML...
InputFormatPlugin: Recipe Input running
Using custom recipe
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
1% Fetching feeds...
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/ebooks/conversion/cli.py", line 401, in main
  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre/ebooks/conversion/plugins/recipe_input.py", line 139, in convert
  File "calibre/web/feeds/news.py", line 1051, in download
  File "calibre/web/feeds/news.py", line 1220, in build_index
  File "<string>", line 340, in parse_index
KeyError: 'resolved_title'
```

**Comment by nhohung** [comment]
Hi @mmagnus,

I made a condition check for `status==2` before appending articles to `arts` (line 339) to eliminate the 'ghost articles'. The code now runs as expected.

Still don't know why the API returns this value of 2 though. I looked up on Pocket API help page but there is not too much detail with key.

```
            for section in section_dict:
                arts = []
                for item in section_dict.get(section):
                    if response['list'][item]['status']=='2':
                        continue
                    
                    arts.append({
                        'title': response['list'][item]['resolved_title'],
                        'url': response['list'][item]['resolved_url'],
                        'date': response['list'][item]['time_added'],
                        'description': response['list'][item]['excerpt'], })

                    if (
                            self.archive_downloaded
                            and response['list'][item]['item_id'] not in self.to_archive
                    ):
                        self.to_archive.append(response['list'][item]['item_id'])

                if not SECTIONS_BY_DOMAIN and SORT_WITHIN_TAG_BY_TITLE:
                    arts = sorted(arts, key=lambda i: i['title'])

                if arts:
                    articles.append((section, arts))
```

**Comment by nhohung** [comment]
Latest investigation update:

Version 2.6.3 does see these `status=2` articles when `TO_PULL = 'all'` and `INCLUDE_UNTAGGED = True`. I contacted Pocket API support but there was no response so far.

In my pull request #38, I've added a commit with a `KeyError` handler that temporary fixes this problem.

The fact that it doesn't failed when `INCLUDE_UNTAGGED = False` (no matter what `TO_PULL` is) means it's something wrong with the way the plugin processes the returned data, not necessarily from Pocket.

Cheers,
Hung

**Comment by nhohung** [comment]
Hi @mmagnus, found it here from line 306:
```
                            try:
                                tag = list(response['list'][item]['tags'].keys())[0]
                            except KeyError:
                                if INCLUDE_UNTAGGED:
                                    tag = 'Untagged'
                                else:
                                    tag = None
```

When `TO_PULL = 'all'`, the API returns all Pockets articles including read (archived), unread, and deleted ones (which has status of 2 and are not shown in the main list). `status=2` articles (hereafter called 'ghost articles') have only 3 keys: unique `item_id`, `status=2` (always), and `listen_duration_estimate=0` (always).

When the plugin hits a ghost article, `KeyError` at line 308 is triggered not only because of missing `response['list'][item]['tags']` but also other missing keys (eg. `resolved_title`, `resolved_url`, etc.) because they don't exist. If `INCLUDE_UNTAGGED = True`, these articles are passed to the next processing stage with `tag='Untagged'` (instead of being filtered out) and will trigger `KeyError` at line 339 when appending article information.

This explains why the error occurs if and only if both `TO_PULL = 'all'` and `INCLUDE_UNTAGGED = True` are met.

## Solution
If we ignore the way Pocket organizes `status` key and just focus on how the plugin deals with `tag`, there are 2 options:
- put a `KeyError` exception when parsing the article information (line 339) like I did in pull request #38
- put an extra condition check for ghost article when handling `INCLUDE_UNTAGGED` (from line 308 quoted above)

I think the second option is the way to go as it makes more sense to filter them out before extracting 'real' article information. What do you think?

**Comment by nhohung** [comment]
I have implemented option 2 to replace option 1 in the pull request #38. The latest commit should handle multi-tag articles and also fix this key missing issue. Please give it a go.
Cheers.
