### ISSUE TITLE
Images are missing or their quality are awful [from habr.com]

### ISSUE THREAD

**Issue by grandsilence** [mmagnus/Pocket-Plus-Calibre-Plugin#49]
Hi. I've got issues with images. Image quality is awful or it's even missing for some articles (loader image placeholder).

Please check spoilers below:

## Missing Images Examples

<details>
  <summary>Missing image example 1</summary>
  
  ![screenshot_2022_01_13T23_20_23+0300](https://user-images.githubusercontent.com/9817522/149422918-bcf2b2cf-7aaa-4807-a6be-1cc5885b5b09.png)
</details>

<details>
  <summary>Missing image example 2</summary>
  
  ![screenshot_2022_01_13T23_26_42+0300](https://user-images.githubusercontent.com/9817522/149422948-4cc6b2d1-cebf-4900-87da-d15d5f76b505.png)
</details>

## Image low quality

<details>
  <summary>Callibre Plugin (issue)</summary>
  
  ![screenshot_2022_01_13T23_23_59+0300](https://user-images.githubusercontent.com/9817522/149423547-3fa9c106-c9db-4b15-8f94-82fe89ada7a9.png)
</details>

<details>
  <summary>Online Service Site: p2k.co (as expected)</summary>

  ![screenshot_2022_01_13T23_22_36+0300](https://user-images.githubusercontent.com/9817522/149423381-e77e35ea-bb03-41a9-b8f5-2108f717c07c.png)
</details>

**Comment by mmagnus** [comment]
dear @grandsilence, does it also happen for other articles (most of them) or this one?

**Comment by grandsilence** [comment]
@mmagnus Most of them on [habr.com](https://habr.com). Here is [the article from screenshot](https://habr.com/ru/post/596373/).  
What information should I provide so that you can reproduce the problem?

**Comment by mmagnus** [comment]
Yeah, I have it. It seems that this page first loads some thumbnails and then load full images. I think for now I don't have an idea how to fix it. It seems also a site-specific bug, so I will keep it open; maybe someone will be able to fix it / help or at some point, I will happen to find a fix/option in Calibre to fix it.

You can also try to run a Recipe specific for this page, like this one:
https://github.com/wistful/calibre-recipes/blob/master/habr.recipe
so maybe they deal with images in a better way.

![sc 2022-02-10 at 09 33 55](https://user-images.githubusercontent.com/118740/153369785-d92b5cb0-905d-4ab2-93e4-583d9b1c45e2.jpg)

**Comment by grandsilence** [comment]
@mmagnus Thank you very much for your reply. I will definitely try the recipe. Is there any way to correct the quality of the images?

**Comment by mmagnus** [comment]
I'm not sure. For other pages everything works, so here it seems we should tell Calibre to wait for full pictures to process into a book, I'm not sure how to do this.

**Comment by grandsilence** [comment]
Thank you. Maybe I'll try to figure it out myself.

чт, 10 февр. 2022 г. в 18:18, Marcin Magnus ***@***.***>:

**Comment by grandsilence** [comment]
@mmagnus Thank you. Maybe I'll try to figure it out myself.
