### ISSUE TITLE
Linux / Raspberry Pi? 

### ISSUE THREAD

**Issue by mikeyreiach** [mmagnus/Pocket-Plus-Calibre-Plugin#50]
Thanks for your work on the plugin. Tried it out on my Mac and it works as expected. I installed the plug in on my Raspberry Pi as it's more likely to be active for a scheduled delivery but it seems that the plug in runs, but there are no articles in the .mobi file. Does it work on Linux / Raspbian? 

I can confirm that the Pocket account was authorized. It did identify tags that I have used, so I know it's connected to my account but the file is only 0.1MB after it "completes" and there are no articles.

**Comment by mmagnus** [comment]
Do you have any log? Maybe indeed Pocket was not authorized.  You can look here, @alvaroreig has something  for Docker, maybe there is more information how to port it to Pi https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/issues/23 @akaped have you tried Calibre/Pocket for Pi?
