### ISSUE TITLE
Keeps stopping... error, very high MAX_ARTICLES_PER_FEED and OLDEST_ARTICLE 

### ISSUE THREAD

**Issue by Yolakalemowa** [mmagnus/Pocket-Plus-Calibre-Plugin#52]
Hi,

Not sure what's wrong... I tried it 4 times and it keeps stopping at the beginning: 6% or 9% or 15%... 

Looking at the job detail doesn't show anything significant it just stops. 

this is my settings is smthn wrong? I picked large numbers to ensure it downloads every single article I have on there:

`
# CONFIGURATION ###########################################################
TAGS = [] # [] or ['tag1', 'tag2']

TAGS_EXCEPTIONS = [] # [] or ['tag3', 'tag4']

SECTIONS_BY_DOMAIN = False

SECTIONS_BY_DOMAIN_USING_TLD = False

INCLUDE_UNTAGGED = True

ARCHIVE_DOWNLOADED = False

MAX_ARTICLES_PER_FEED = 9999999999

OLDEST_ARTICLE = 99999999999

SORT_METHOD = 'newest'

SORT_WITHIN_TAG_BY_TITLE = False

TO_PULL = 'unread'

TITLE_WITH_TAGS = False

ALLOW_DUPLICATES = True

USE_GLOBAL_CONFIG = False
`

**Comment by mmagnus** [comment]
Yeah @Yolakalemowa maybe these numbers are too high. I don't use so high numbers so maybe there are some issues with the performance of the code, that we usually don't see. 

Can you try with the default values (for MAX_ARTICLES_PER_FEED   OLDEST_ARTICLE) and TO_PULL = 'unread' to see if the high numbers are the problem?
