### ISSUE TITLE
Unable to grant access to pocket account

### ISSUE THREAD

**Issue by k-r-a-s-s** [mmagnus/Pocket-Plus-Calibre-Plugin#55]
I'm trying to get my pocket account connected.
I've followed the instructions but I'm getting the following dialog box after clikcing 'fetch news' (with the recipe):

<img width="605" alt="image" src="https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/assets/91785539/f8fd4f9d-0570-4355-aec4-99312406249b">

Instead of what I expected, the screenshot from the readme:
https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/raw/master/doc/grant.png

Copy paste of the error:

calibre, version 6.28.1 (darwin, embedded-python: True)
Conversion error: Failed: Fetch news from Pocket

Fetch news from Pocket
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  verbose: 2
Resolved conversion options
calibre version: 6.28.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_download_recipe': False,
 'dont_split_on_page_breaks': True,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_max_image_size': 'none',
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x113746d10>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x113747010>,
 'page_breaks_before': None,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'transform_html_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Downloading recipe urn: custom:1000
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Traceback (most recent call last):
  File "<string>", line 252, in authorize
  File "mechanize/_mechanize.py", line 257, in open
  File "mechanize/_mechanize.py", line 313, in _mech_open
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_recipe
  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/recipe_input.py", line 137, in convert
  File "calibre/web/feeds/news.py", line 941, in __init__
  File "<string>", line 423, in get_browser
  File "<string>", line 418, in ensure_authorization
  File "<string>", line 262, in authorize
  File "<string>", line 406, in reauthorize
  File "<string>", line 412, in ensure_authorization
  File "calibre/web/feeds/news.py", line 846, in abort_recipe_processing
calibre.ebooks.conversion.ConversionUserFeedBack: {"msg": "\n                                Calibre must be granted access to your Pocket account. Please click\n                                <a href=\"https://getpocket.com/auth/authorize?request_token=0c6e9296-4c18-cb50-fb54-64d3c3&redirect_uri=https://calibre-ebook.com/\">here</a>\n                                to authenticate via a browser, and then re-fetch the news.\n                        ", "level": "info", "det_msg": "", "title": "Failed to download Pocket"}
Using proxies: {'http': '127.0.0.1:7769', 'https': '127.0.0.1:7769'}

**Comment by mmagnus** [comment]
I think the only solution is to keep trying. It works for me, and at some point I had the same problem to login that disappear...
