### ISSUE TITLE
cannot access local variable 'response' where it is not associated with a value (bad request)

### ISSUE THREAD

**Issue by alvaroreig** [mmagnus/Pocket-Plus-Calibre-Plugin#56]
Hi there @mmagnus 

Since yesterday the recipe fails:

`UnboundLocalError: cannot access local variable 'response' where it is not associated with a value`

This line is the cause:

 response = self.browser.open(request)

Which is responding:

`HTTP Error 400: Bad Request`

The request is built with

```
                request = mechanize.Request("https://getpocket.com/v3/get",
                                        (u'{{'
                                                '"consumer_key":"{0}",'
                                                '"access_token":"{1}",'
                                                '"count":"{2}",'
                                                '"since":"{3}",'
                                                '"state":"{5}",'
                                                '"detailType":"complete",'
                                                '"sort":"{4}"' '}}').format(
                                                self.consumer_key,
                                                self.config.token,
                                                self.max_articles_per_feed * 1000,  # something "unlimited"
                                                int(time()) - 86400 * self.oldest_article,
                                                self.sort_method, 
                                                self.to_pull,
                                        ),
                                        headers = {
                                                'Content-Type': 'application/json; charset=UTF8',
                                                'X-Accept': 'application/json'
                                        }
                                )
```
I tried deleting and generating the token again, but it still fails.

More debugging is needed, but it seems that pocket has changed something in the API

**Comment by mmagnus** [comment]
OK, this also explains why my favorite Mac Pocket app also does not work.. eh :( 

![sc 2024-07-13 at 20 11 28](https://github.com/user-attachments/assets/a3af3ac2-01dc-428f-8758-a830566af0a5)

**Comment by alvaroreig** [comment]
I've been querying the API from postman:

![image](https://github.com/user-attachments/assets/0f33544b-4b52-48cc-9868-2a7fef6470c4)

And it's returning a 400 error complaining about a "filter" variable, which is not listed in the API documentation:

https://getpocket.com/developer/docs/v3/retrieve

I've just written to their API email, it might be a new variable not yet documented, or an error.

**Comment by alvaroreig** [comment]
Hi there,

After receiving response from Pocket support (thanks Kat), I realized that the problem was in the "count" parameter. I had built the test case wrong (incorrect "since" parameter), after correcting it the error was obvious)

We are calculating that value with:

`self.max_articles_per_feed * 1000,  # something "unlimited"`

So if you are using a max_articles_per_feed of, say, 1000, the "count" is 1.000.000, which is too much and the pocket API rejects the request:

`"error": "Invalid value: {\"location\":\"body\",\"path\":\"count\",\"type\":\"field\",\"value\":40000000}"
`

So setting my MAX_ARTICLES_PER_FEED to 4 solves the issue.

The thing is, we named that parameter MAX_ARTICLES_PER_FEED, but we don't actually used it for that. We just multiple it by 1000 and use it to query the Pocket api. So I would rename it to MAX_ARTICLES_TO_FETCH and remove the "1000" multiplier.

Do you agree @mmagnus ?

**Comment by alvaroreig** [comment]
I changed the limit to fix the issue.

**Comment by mmagnus** [comment]
It works even with my own old version. I think the Pocket fixed something on the own side. Great! Thanks @alvaroreig for your work!
